server:
  port: 10087
spring:
  application:
    name: itcast-eureka
eureka:
  client:
    service-url: # \u5E94\u7528\u540D\u79F0\uFF0C\u6CE8\u518C\u5230eureka\u540E\u7684\u670D\u52A1\u540D\u79F0
       defaultZone: http://127.0.0.1:10086/eureka