server:
  port: 80
spring:
  application:
    name: service-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # \u8BBE\u7F6Ehystrix\u7684\u8D85\u65F6\u65F6\u95F4\u4E3A6000ms

feign:
  hystrix:
    enabled: true # \u5F00\u542FFeign\u7684\u7194\u65AD\u529F\u80FD