server:
  port: 8081
mybatis:
  type-aliases-package: cn.itcast.service.pojo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: root
  application:
    name: service-provider # 应用名称，注册到eureka后的服务名称
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka